#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

base_url="https://raw.githubusercontent.com/git/git/master/contrib/completion"
completion="git-completion.bash"
prompt="git-prompt.sh"

_install() {
  wget --quiet -nc -P $DIR $base_url/$1
  ln -fs $DIR/$1 ~/.$1
}

if [ -x "$(command -v git)" ]; then
  echo 'git is installed, skipping'
else
  sudo apt-get install git
fi

_install $prompt
_install $completion

ln -sf $DIR/gitignore $HOME/.gitignore
ln -sf $DIR/gitconfig $HOME/.gitconfig
ln -sf $DIR/git-prompt.sh $HOME/.git-prompt.sh
ln -sf $DIR/git-completion.bash $HOME/.git-completion.bash
