#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

base_url="https://raw.githubusercontent.com/git/git/master/contrib/completion"
completion="git-completion.bash"
prompt="git-prompt.sh"

_install() {
  wget --quiet -nc -P $DIR $base_url/$1
  ln -fs $DIR/$1 ~/.$1
}

sudo apt-get install git

_install $prompt
_install $completion
