#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
vundle_dir="$HOME/.vim/bundle/Vundle.vim"

if [ ! -d $vundle_dir ]; then
  git clone https://github.com/gmarik/Vundle.vim.git $vundle_dir
fi

mkdir -p $HOME/.vim/{undos,swap,backups}
ln -sf $DIR/vimrc $HOME/.vimrc
ln -sf $DIR/ideavimrc $HOME/.ideavimrc
