set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin '907th/vim-auto-save'
Plugin 'altercation/vim-colors-solarized'
Plugin 'AndrewRadev/linediff.vim'
Plugin 'easymotion/vim-easymotion'
Plugin 'elzr/vim-json'
Plugin 'gcmt/wildfire.vim'
Plugin 'gmarik/Vundle.vim'
Plugin 'godlygeek/tabular'
Plugin 'haya14busa/incsearch-easymotion.vim'
Plugin 'haya14busa/incsearch-fuzzy.vim'
Plugin 'haya14busa/incsearch.vim'
Plugin 'honza/vim-snippets'
Plugin 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plugin 'junegunn/fzf.vim'
Plugin 'junegunn/limelight.vim'
Plugin 'kien/ctrlp.vim'
Plugin 'majutsushi/tagbar' " sudo apt-get install ctags
Plugin 'mkitt/tabline.vim'
Plugin 'nvie/vim-flake8'
Plugin 'scrooloose/nerdtree'
Plugin 'jistr/vim-nerdtree-tabs'
Plugin 'scrooloose/syntastic'
Plugin 'simnalamburt/vim-mundo'
Plugin 'SirVer/ultisnips'
Plugin 'tmux-plugins/vim-tmux'
Plugin 'tpope/vim-repeat'
Plugin 'tpope/vim-surround'
Plugin 'Valloric/YouCompleteMe'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
call vundle#end()

set nocompatible
filetype plugin indent on
filetype off
if has("syntax")
  syntax on
endif
set undodir=$HOME/.vim/undos
set undofile
set directory=$HOME/.vim/swap
set noswapfile
set backupdir=$HOME/.vim/backups
set backupskip=/tmp/*,/private/tmp/* " http://vim.wikia.com/wiki/Editing_crontab
set backup
set linespace=0
set splitbelow
set splitright
set tabstop=4
set expandtab
set shiftwidth=4
set visualbell
set ttyfast
set laststatus=2
set hlsearch
set ignorecase
set smartcase
set foldmethod=indent
set foldlevel=99
set encoding=utf-8
set clipboard=unnamedplus
set backspace=indent,eol,start
set number
set shortmess=atI
set t_Co=256

" searches use normal regexes
nnoremap / /\v
vnoremap / /\v

"autocmd BufEnter * silent! lcd %:p:h
autocmd VimEnter * NERDTree
autocmd VimEnter * wincmd w
autocmd BufEnter * set mouse=
autocmd FileType sh setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType json setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType python setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType *.conf setlocal ts=2 sts=2 sw=2 expandtab
"autocmd VimEnter * NERDTreeTabsToggle

"map <Leader>n <plug>NERDTreeTabsToggle<CR>

let g:solarized_termtrans=1
let g:solarized_termcolors=256
let g:solarized_visibility='high'
let g:solarized_contrast='high'
colorscheme solarized
set background=dark

let g:airline_powerline_fonts=1
let g:airline_solarized_bg='dark'
let g:airline_left_sep=''
let g:airline_right_sep=''

let python_highlight_all=1

let NERDTreeMinimalUI=1
let NERDTreeDirArrows=1
let NERDTreeAutoDeleteBuffer=1
let g:NERDTreeHijackNetrw=1
let NERDTreeIgnore = ['\.pyc$', '\.classyc$', '__init__.py']
highlight NERDTreeOpenable ctermfg=1
au VimEnter NERD_tree_1 enew | execute 'NERDTree '.argv()[0]

let g:nerdtree_tabs_open_on_console_startup=1
let g:nerdtree_tabs_no_startup_for_diff=0

let mapleader=' '
let g:ctrlp_cmd='CtrlPBuffer'

let g:wildfire_objects = ["iW", "i'", 'i"', "i)", "i]", "i}", "ip", "it"]

let g:auto_save=1
let g:auto_save_in_insert_mode=0
let g:auto_save_silent=1

let g:mundo_right=1
let g:mundo_close_on_revert=1

let g:vim_json_syntax_conceal=2

let g:UltiSnipsExpandTrigger='<tab>'
let g:UltiSnipsJumpForwardTrigger='<c-tab>'
let g:UltiSnipsJumpBackwardTrigger='<s-tab>'

let g:ycm_collect_identifiers_from_tags_files=1 " Let YCM read tags from Ctags file
let g:ycm_use_ultisnips_completer=1 " Default 1, just ensure
let g:ycm_seed_identifiers_with_syntax=1 " Completion for programming language's keyword
let g:ycm_complete_in_comments=1 " Completion in comments
let g:ycm_complete_in_strings=1 " Completion in string
let g:ycm_autoclose_preview_window_after_completion=1
let g:ycm_collect_identifiers_from_comments_and_strings=1
let g:ycm_key_list_select_completion = ['<C-j>', '<Down>']
let g:ycm_key_list_previous_completion = ['<C-k>', '<Up>']

let g:limelight_conceal_ctermfg = 'gray'
let g:limelight_conceal_ctermfg = 240

" <Leader>f{char} to move to {char}
map  <leader>f <Plug>(easymotion-bd-f)
nmap <leader>f <Plug>(easymotion-overwin-f)

" Move to line
map <leader>L <Plug>(easymotion-bd-jk)
nmap <leader>L <Plug>(easymotion-overwin-line)

" Move to word
map  <leader>w <Plug>(easymotion-bd-w)
nmap <leader>w <Plug>(easymotion-overwin-w)

map <leader>/ <Plug>(incsearch-fuzzy-/)

map <C-b> :YcmCompleter GoTo<CR>

noremap <silent><expr> <Leader>/ incsearch#go(<SID>config_easyfuzzymotion())
noremap H ^
noremap L $
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
nnoremap <BS> :nohlsearch<CR>
nnoremap <C-N> :MundoToggle<CR>
nnoremap <leader>1 1gt<CR>
nnoremap <leader>2 2gt<CR>
nnoremap <leader>3 3gt<CR>

inoremap <Up> <Nop>
inoremap <Down> <Nop>
inoremap <Left> <Nop>
inoremap <Right> <Nop>
"inoremap <BS> <Nop>
inoremap jj <ESC>

vnoremap < <gv
vnoremap > >gv

nmap <silent> <C-T> :NERDTreeToggle<CR>
nmap <leader>q :q<CR>
nmap <leader>Q :qa<CR>
nmap <leader>+ zo
nmap <leader>- zc
nmap <leader>l :tabnext<CR>
nmap <leader>h :tabprevious<CR>

" Toggle invisible chars
map <leader>tl :set list!<CR>
map <leader>r :NERDTreeFind<cr>
nmap <leader>a <Plug>(wildfire-quick-select)
nmap <F8> :TagbarToggle<CR>

" fzf
map <leader>b :Buffers<CR>
map <leader>o :Files<CR>

" fuzzy-search with EasyMotion
function! s:config_easyfuzzymotion(...) abort
  return extend(copy({
  \   'converters': [incsearch#config#fuzzyword#converter()],
  \   'modules': [incsearch#config#easymotion#module({'overwin': 1})],
  \   'keymap': {"\<CR>": '<Over>(easymotion)'},
  \   'is_expr': 0,
  \   'is_stay': 1
  \ }), get(a:, 1, {}))
endfunction
