#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
scripts_dir="$HOME/.i3/scripts"

__install() {
  if [ -x "$(command -v i3)" ]; then
    echo 'i3 is installed, skipping'
  else
    sudo apt-get install i3
  fi
}

__configure() {
  if [ ! -d  $scripts_dir ]; then
    mkdir -p $HOME/.i3/scripts
  fi

  ln -s $DIR/config $HOME/.i3/config
  ln -s $DIR/i3blocks.conf $HOME/.i3/i3blocks.conf
  ln -s $DIR/scripts/* $HOME/.i3/scripts/
}

__install
__configure
