#!/usr/bin/env bash

command -v xrandr > /dev/null 2>&1 || {
  echo >&2 "automon: I require xrandr, but it's not installed. Aborting.";
  exit 1;
}

function usage() {
    echo "Usage: automon OPTION"
    echo ""
    echo "Options"
    echo "    -a, --above"
    echo "        Place the secondary monitor above the primary"
    echo ""
    echo "    -b, --below"
    echo "        Place the secondary monitor below the primary"
    echo ""
    echo "    -l, --left"
    echo "        Place the secondary monitor to the left of the primary"
    echo ""
    echo "    -r, --right"
    echo "        Place the secondary monitor to the right of the primary"
    echo ""
    echo "    -s, --same"
    echo "        Show the same thing on both monitors"
    echo ""
}

if [[ "$#" != 1 ]]; then
    usage
    exit 1
fi

xrandr --auto

primary=$(xrandr | grep ' connected primary ' | cut --delimiter ' ' --fields 1)

secondary=$(xrandr | grep ' connected ' | grep --invert-match 'primary' | cut --delimiter ' ' --fields 1)

number_of_secondary_monitors=$(xrandr | grep ' connected ' | grep --invert-match ' connected primary ' | wc --lines)

if [[ $number_of_secondary_monitors != 1 ]]; then
    echo "automon: Expected to find one secondary monitor but found $number_of_secondary_monitors, aborting."
    exit 1
fi

case $1 in
    -a | --above )
        xrandr --output "$secondary" --above "$primary"
        ;;
    -b | --below )
        xrandr --output "$secondary" --below "$primary"
        ;;
    -l | --left )
        xrandr --output "$secondary" --left-of "$primary"
        ;;
    -r | --right )
        xrandr --output "$secondary" --right-of "$primary"
        ;;
    -s | --same )
        xrandr --output "$secondary" --same-as "$primary"
        ;;
    * )
        usage
        exit 1
esac
