#!/usr/bin/env bash

command -v gnome-screenshot > /dev/null 2>&1 || {
  echo >&2 "display: I require gnome-screenshot, but it's not installed. Aborting.";
  exit 1;
}

function usage() {
  echo "Usage: screenshot [options]"
  echo "" 
  echo "Options"
  echo "-a, --area"
  echo "    Grab an area of the screen instead of the entire screen"
  echo "-w, --window"
  echo "    Grab an area of the screen instead of the entire screen"
}

while [ "$1" != "" ]; do
  case $1 in
    -a | --area )
      gnome-screenshot -a
      ;;
    -w | --window )
      gnome-screenshot -w
      ;;
    -h | --help )
      usage
      exit
      ;;
  esac
  shift
done
