#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ ! -d "$HOME/.fzf" ]; then
  git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
  ~/.fzf/install
fi

ln -s $SCRIPT_DIR/../fzf/fzf_magic_completion.bash ~/.fzf/shell/fzf_magic_completion.bash
