#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

completion_dir="$DIR/bash_completion.d"
completions=(
  "https://raw.githubusercontent.com/Bash-it/bash-it/master/completion/available/tmux.completion.bash"
  "https://raw.githubusercontent.com/Bash-it/bash-it/master/completion/available/maven.completion.bash"
  "https://raw.githubusercontent.com/Bash-it/bash-it/master/completion/available/ssh.completion.bash"
  "https://raw.githubusercontent.com/gradle/gradle-completion/master/gradle-completion.bash"
)

if [ ! -d $completion_dir ]; then
  mkdir $completion_dir
fi

if [ ! -f ~/.bash_completion ]; then
  ln -v -s $DIR/bash_completion ~/.bash_completion
fi

if [ ! -d "$HOME/.bash_completion.d" ]; then
  mkdir $HOME/.bash_completion.d
fi

for uri in "${completions[@]}" ; do
  file_name=$(echo $uri | grep -Po '([\w-.]*\.bash)$')
  if [ ! -f $completion_dir/$file_name ]; then
    echo "Downloading: " $uri
    curl --silent --url $uri --output $completion_dir/$file_name
    ln -v -s $DIR/bash_completion.d/$file_name $HOME/.bash_completion.d
  fi
done
