#!/usr/bin/env bash

__usage() {
  echo "Usage: install [options]"
  echo ""
  echo "Options"
  echo "-f, --force"
  echo "    Force tmux installation"
  echo "-h, --help"
  echo "    Print this usage"
}

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
VERSION=2.8
tpm_dir="$HOME/.tmux/plugins/tpm"

__install_tmux() {
  sudo apt-get -y remove tmux
  sudo apt-get -y install wget tar libevent-dev libncurses-dev
  wget https://github.com/tmux/tmux/releases/download/${VERSION}/tmux-${VERSION}.tar.gz
  tar xf tmux-${VERSION}.tar.gz
  rm -f tmux-${VERSION}.tar.gz
  cd tmux-${VERSION}
  ./configure
  make
  sudo make install
  cd -
  sudo rm -rf /usr/local/src/tmux-*
  sudo mv tmux-${VERSION} /usr/local/src
}

__install_tpm() {
  if [ ! -d $tpm_dir ]; then
    git clone https://github.com/tmux-plugins/tpm $tpm_dir 
    $tpm_dir/bin/install_plugins
  else
    echo 'tpm already exists'
  fi
}

__install() {
  if [ -x "$(command -v gcc)" ]; then
    echo 'gcc is installed, skipping'
  else
    sudo apt-get -y install gcc
  fi
  if [ -x "$(command -v make)" ]; then
    echo 'make is installed, skipping'
  else
    sudo apt-get -y install make
  fi
  if [[ ! $force ]] && [ -x "$(command -v gcc)" ]; then
    echo 'tmux is installed, skipping'
  else
    __install_tmux
  fi
}

while [ "$1" != "" ]; do
  case $1 in
    -f | --force)
      shift
      force=true
      ;;
    -h | --help )
      __usage
      exit
      ;;
    * )
      __usage
      exit
      ;;
  esac
  shift
done

__install
__install_tpm

ln -sf $DIR/tmux.conf $HOME/.tmux.conf
