#!/usr/bin/env bash

VERSION=2.7
tpm_dir="$HOME/.tmux/plugins/tpm"

__install_tmux() {
  sudo apt-get -y remove tmux
  sudo apt-get -y install wget tar libevent-dev libncurses-dev
  wget https://github.com/tmux/tmux/releases/download/${VERSION}/tmux-${VERSION}.tar.gz
  tar xf tmux-${VERSION}.tar.gz
  rm -f tmux-${VERSION}.tar.gz
  cd tmux-${VERSION}
  ./configure
  make
  sudo make install
  cd -
  sudo rm -rf /usr/local/src/tmux-*
  sudo mv tmux-${VERSION} /usr/local/src
}

__install_tpm() {
  git clone https://github.com/tmux-plugins/tpm $tpm_dir 
}

if [ -x "$(command -v tmux)" ]; then
  echo 'tmux is installed, skipping'
else
  __install_tmux
fi

if [ ! -d $tpm_dir ]; then
  __install_tpm
else
  echo 'tpm already exists'
fi

ln -s $DIR/tmux/tmux.conf $HOME/.tmux.conf
