alias ..='cd ..'
alias ...='cd ../../'
alias .3='cd ../../../'
alias ~='cd ~'

alias c='clear'

alias rmr='rm -ri'

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -l'

alias cp='cp -iv'
alias mv='mv -iv'
alias mkdir='mkdir -pv'

alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias cpwd='pwd | tr -d "\n" | xclip'

alias __list_open_ports='sudo lsof -i | grep LISTEN'
alias __fix_line_endings='find ./ -type f -exec dos2unix {} \;'

alias idea='bash -c "nohup idea.sh . >/dev/null 2>&1 &"'

alias mci='mvn clean install'
alias mcid='mvn clean install -Ddockerfile.skip'
alias mjr='mvn jetty:run'
alias mvs='mvn versions:set'
alias mvc='mvn versions:commit'
alias msr='mvn spring-boot:run'
alias mdt='mvn dependency:tree'

alias d='docker'
alias drm='docker rm'
alias drmi='docker rmi'
alias dv='docker volume'
alias dn='docker network'
alias dsp='docker system prune'
alias doco='docker-compose'

alias vimrc='vim ~/.vimrc'

alias xclip='xclip -selection clipboard'

alias fvim='vim $(fzf)'
alias fv='fvim'
alias gcb='git checkout $(git branch | fzf)'
alias gcf='git checkout -- $(git diff --name-only --relative | fzf)'

alias k="kubectl"
alias kc='k config view | grep current-context | tr -s " " | cut -f 2 -d " "'

alias kexec='k exec -it $(kubectl --context $(kc) get pods | fzf) -- /bin/bash'
#alias klogs='k logs -f $(kubectl --context $(kc) get pods | fzf)'
alias kgrep='k --context $(kc) get pods | grep $1'
