# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi
# set PATH so it includes user's private bin directories
PATH="$PATH:$HOME/bin:$HOME/.local/bin"

export EDITOR=/usr/bin/vim

# Java
export JAVA_HOME="/usr/lib/jvm/default-java"
#export JAVA_HOME="/usr/lib/jvm/java-1.8.0-openjdk-amd64"
#export JAVA_HOME="/usr/lib/jvm/jdk-11.0.6+10"
export PATH="$JAVA_HOME/bin:$PATH"

# Maven
export M2_HOME="/opt/maven"
export MAVEN_OPTS="-Xms4g -Xmx4g"
export PATH="$PATH:$M2_HOME/bin"

# Gradle
export PATH="$PATH:/opt/gradle/bin"

# Intellij
export PATH="$PATH:/opt/idea/bin"

alias img_check='/home/joakim/code/command-line-tools/bash/img_check.sh'
export KUBECONFIG=/home/joakim/.kube/config:/home/joakim/.kube/config.lab:/home/joakim/.kube/config.dev:/home/joakim/.kube/config.qa:/home/joakim/.kube/config.stage:/home/joakim/.kube/config.prod

source ~/bin/kubectx.bash_completion
source ~/bin/kubens.bash_completion
