alias ..='cd ..'
alias ...='cd ../../'
alias .3='cd ../../../'
alias ~='cd ~'

alias c=clear

alias rmr='rm -ri'

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -l'

alias cp='cp -iv'
alias mv='mv -iv'
alias mkdir='mkdir -pv'

alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias cpwd='pwd | tr -d "\n" | pbcopy'

alias openPorts='sudo lsof -i | grep LISTEN'

alias fix-line-endings='find ./ -type f -exec dos2unix {} \;'

alias idea='nohup idea.sh . >/dev/null 2>&1 &'

alias mci='mvn clean install'
alias mcid='mvn clean install -Ddockerfile.skip'
alias mjr='mvn jetty:run'
alias mvs='mvn versions:set'
alias mvc='mvn versions:commit'
alias msr='mvn spring-boot:run'

alias vimrc='vim ~/.vimrc'

alias xclip='xclip -selection clipboard'

alias nh='nohup $@ > /dev/null &'

# fzf
alias fvim='vim $(fzf)'
alias fv='fvim'
alias gcb='git checkout $(git branch | fzf)'
alias gcf='git checkout -- $(git diff --name-only | fzf)'
