#!/usr/bin/env bash

gradle_version="7.3.3"
gradle_dir_name="gradle-$gradle_version"
full_zip_file_name="$gradle_dir_name-all.zip"
url="https://services.gradle.org/distributions/$full_zip_file_name"
install_dir="/opt"

__install() {
  tar_file="$install_dir/$full_zip_file_name"
  full_install_path="$install_dir/$gradle_dir_name"

  if [ ! -f "$tar_file" ]; then
    echo "Downloading $full_zip_file_name to $tar_file"
    wget -c -P $install_dir $url
  else
    echo "$full_zip_file_name already exists, not downloading"
  fi

  if [ ! -d "$full_install_path" ]; then
      unzip $tar_file -d $install_dir
      echo "Extracted $tar_file to $full_install_path"
  else
      echo "Not extracting $tar_file since $full_install_path exists"
  fi

  symlink_gradle_file="$install_dir/gradle"
  rm $symlink_gradle_file
  ln -sf $full_install_path $symlink_gradle_file
  echo "Symlink $symlink_gradle_file created for $full_install_path"
}

__install
