#!/usr/bin/env bash

sudo add-apt-repository ppa:openjdk-r/ppa
sudo apt-get update
sudo apt-get install openjdk-11-jdk
sudo update-alternatives --config java 

sudo ln -sf /usr/lib/jvm/java-11-openjdk-amd64/ /usr/lib/jvm/default-java
